tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'neovim/neovim'
tap 'ravenac95/sudolikeaboss'
brew 'autoconf'
brew 'automake'
brew 'cmake'
brew 'gdbm'
brew 'gettext'
brew 'git'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'jemalloc'
brew 'openssl'
brew 'libevent'
brew 'libtermkey'
brew 'libtool'
brew 'libuv'
brew 'libvterm'
brew 'mackup'
brew 'mas'
brew 'msgpack'
brew 'pkg-config'
brew 'shellcheck'
brew 'unibilium'
brew 'wget'
brew 'zsh'
brew 'ravenac95/sudolikeaboss/sudolikeaboss'
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'bartender'
cask 'bee'
cask 'bettertouchtool'
cask 'boxcryptor'
cask 'cakebrew'
cask 'choosy'
cask 'cocoarestclient'
cask 'cryptomator'
cask 'cyberduck'
cask 'dash'
cask 'docker-toolbox'
cask 'dropbox'
cask 'flux'
cask 'fork'
cask 'hazel'
cask 'iterm2'
cask 'kaleidoscope'
cask 'kextviewr'
cask 'keybase'
cask 'little-snitch'
cask 'macdown'
cask 'mplayerx'
cask 'osxfuse'
cask 'slack'
cask 'sublime-text'
cask 'taskexplorer'
cask 'torbrowser'
cask 'tower'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'viscosity'
cask 'zoomus'
mas 'Unclutter', id: 577085396
mas 'The Unarchiver', id: 425424353
mas 'Keynote', id: 409183694
mas 'Haskell', id: 841285201
mas 'Patterns', id: 429449079
mas 'Wunderlist', id: 410628904
mas 'Deliveries', id: 924726344
mas 'Slack', id: 803453959
mas 'Pages', id: 409201541
mas 'Pixelmator', id: 407963104
mas 'Textual', id: 896450579
mas 'Home Inventory', id: 413564952
mas 'Reeder', id: 880001334
mas '1Blocker', id: 1107421413
mas 'Numbers', id: 409203825
